"""Render recorded business evaluations into the Harbor viewer's trial summary.

The viewer builds its trial summary from `<trial>/analysis.md`; it never reads our
`sapi-lab-task-evaluation/v1` rubric. This command writes that derived Markdown
view beside the frozen evidence. It adds files only: no recorded artifact is
rewritten, and `evaluation.json` itself is read-only here.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

from sapi_config_lab.core.evidence import json_text

SCHEMA = "sapi-lab-task-evaluation/v1"
GENERATED = "<!-- Generated by `sapi-lab review-export`. Derived view, not recorded evidence. -->"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def find_evaluations(jobs_dir: Path) -> list[Path]:
    """Locate every trial that recorded a business evaluation."""
    return sorted(jobs_dir.glob("*/*/verifier/evaluation.json"))


def table(rows: list[list[str]], headers: list[str]) -> str:
    cells = [headers, ["---"] * len(headers), *rows]
    return "\n".join("| " + " | ".join(row) + " |" for row in cells)


def escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def render(evaluation: dict, source: Path) -> str:
    score = evaluation.get("score_0_10")
    judge = evaluation.get("judge") or {}
    criteria = evaluation.get("criteria") or []
    acceptance = evaluation.get("project_acceptance") or {}

    deterministic = [c for c in criteria if c.get("evaluator") == "deterministic"]
    judged = [c for c in criteria if c.get("evaluator") != "deterministic"]
    earned = sum(float(c.get("points") or 0) for c in criteria)
    available = sum(float(c.get("weight") or 0) for c in criteria)

    lines = [
        GENERATED,
        "",
        f"# Business evaluation — {score}/10",
        "",
        f"- **Normalized reward:** {evaluation.get('normalized_reward')}",
        f"- **Status:** {evaluation.get('status')}",
        f"- **Engine execution passed:** {evaluation.get('execution_pass')}",
        f"- **Points:** {earned:g} of {available:g} ({len(deterministic)} deterministic, {len(judged)} judged)",
        f"- **Deterministic points:** {evaluation.get('deterministic_points')}",
        "",
        "Engine execution and acceptance are separate. A passing execution does not",
        "establish the score below, and the score does not claim the run was error-free.",
        "",
        "## Criteria",
        "",
        table(
            [
                [
                    escape(c.get("id")),
                    escape(c.get("question")),
                    escape(c.get("evaluator")),
                    escape(c.get("answer")),
                    f"{float(c.get('points') or 0):g} / {float(c.get('weight') or 0):g}",
                    escape(c.get("reason")),
                    escape(", ".join(c.get("evidence_refs") or [])) or "—",
                ]
                for c in criteria
            ],
            ["ID", "Question", "Evaluator", "Answer", "Points", "Reason", "Evidence"],
        ),
        "",
        f"Answer values: {json.dumps(evaluation.get('answer_values') or {})}",
        "",
    ]

    if acceptance:
        lines += [
            "## Project acceptance",
            "",
            f"- **Criterion:** {acceptance.get('criterion')}",
            f"- **Passed:** {acceptance.get('passed')}",
            f"- **Affects upstream score:** {acceptance.get('affects_upstream_score')}",
            f"- **Reason:** {acceptance.get('reason')}",
            "",
        ]

    if evaluation.get("judge_error"):
        lines += ["## Judge error", "", f"```\n{evaluation['judge_error']}\n```", ""]

    lines += [
        "## Provenance",
        "",
        f"- **Run:** `{evaluation.get('run_id')}`",
        f"- **Evaluation mode:** {evaluation.get('evaluation_mode')}",
        f"- **Judge:** {judge.get('mode')} / {judge.get('model')} / prompt {judge.get('prompt_version')}",
        f"- **Contract digest:** `{evaluation.get('contract_digest')}`",
        f"- **Run log digest:** `{evaluation.get('run_log_digest')}`",
        f"- **Source:** `{source.name}`, sha256 `{digest(source)}`",
        "",
    ]
    return "\n".join(lines)


def reward_files(evaluation: dict) -> dict[str, dict]:
    """Populate the viewer's documented verifier-output endpoint.

    This build's bundled frontend never requests that endpoint, so these files
    are written only on request.
    """
    criteria = evaluation.get("criteria") or []
    return {
        "reward.json": {"reward": evaluation.get("normalized_reward")},
        "reward-details.json": {
            "reward": evaluation.get("normalized_reward"),
            "score_0_10": evaluation.get("score_0_10"),
            "components": [
                {
                    "name": c.get("id"),
                    "score": c.get("points"),
                    "max": c.get("weight"),
                    "answer": c.get("answer"),
                    "evaluator": c.get("evaluator"),
                    "rationale": c.get("reason"),
                }
                for c in criteria
            ],
        },
    }


def export_trial(evaluation_path: Path, *, force: bool, rewards: bool, dry_run: bool) -> dict:
    trial = evaluation_path.parent.parent
    evaluation = json.loads(evaluation_path.read_text())
    row: dict[str, Any] = {"trial": trial.name, "job": trial.parent.name, "written": [], "skipped": []}
    if evaluation.get("schema") != SCHEMA:
        row["skipped"].append({"path": "analysis.md", "reason": f"Unexpected schema {evaluation.get('schema')!r}"})
        return row

    targets: dict[Path, str] = {trial / "analysis.md": render(evaluation, evaluation_path)}
    if rewards:
        for name, value in reward_files(evaluation).items():
            targets[trial / "verifier" / name] = json_text(value)

    for path, content in targets.items():
        relative = str(path.relative_to(trial))
        if path.exists() and not force:
            row["skipped"].append({"path": relative, "reason": "Exists; use --force to replace"})
            continue
        if not dry_run:
            path.write_text(content)
        row["written"].append(relative)
    return row


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("jobs_dir", type=Path, help="A Harbor jobs directory, as passed to `harbor view`")
    parser.add_argument("--force", action="store_true", help="Replace a derived file this command wrote before")
    parser.add_argument("--rewards", action="store_true", help="Also write reward.json and reward-details.json")
    parser.add_argument("--dry-run", action="store_true", help="Report what would be written; change nothing")
    args = parser.parse_args()

    jobs_dir = args.jobs_dir.resolve()
    if not jobs_dir.is_dir():
        raise ValueError("Pass an existing Harbor jobs directory")
    evaluations = find_evaluations(jobs_dir)
    rows = [export_trial(path, force=args.force, rewards=args.rewards, dry_run=args.dry_run) for path in evaluations]
    print(
        json.dumps(
            {
                "jobs_dir": str(jobs_dir),
                "evaluations_found": len(evaluations),
                "dry_run": args.dry_run,
                "trials": rows,
            },
            indent=2,
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
