"""Render recorded evaluations as `<trial>/analysis.md`, the Harbor viewer's trial summary.

Derived files only: no recorded artifact is rewritten.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

from sapi_config_lab.evaluate.records import recorded_path
from sapi_config_lab.evidence import json_text, sha256

SCHEMA = "sapi-lab-task-evaluation/v1"
HOSTED_SCHEMA = "sapi-lab-upstream-acceptance/v1"
GENERATED = "<!-- Generated by `sapi-lab review-export`. Derived view, not recorded evidence. -->"


def find_evaluations(jobs_dir: Path) -> list[tuple[Path, Path]]:
    """Prefer the run's authoritative association over container copies."""
    found = {path.parents[2]: path for path in jobs_dir.glob("*/*/verifier/evaluation/evaluation.json")}
    for source in jobs_dir.glob("*/*/verifier/evaluation/report.json"):
        if json.loads(source.read_text()).get("schema") == HOSTED_SCHEMA:
            found[source.parents[2]] = source

    def visit(value: Any) -> None:
        if isinstance(value, list):
            for item in value:
                visit(item)
        elif isinstance(value, dict):
            if value.get("result_path") and value.get("task_name"):
                trial = (
                    recorded_path(value["trial_path"], jobs_dir.parent)
                    if value.get("trial_path")
                    else recorded_path(value["result_path"], jobs_dir.parent).parent
                )
                if trial.is_relative_to(jobs_dir):
                    # Older runs predate the explicit association but retained the same host layout.
                    source = (
                        trial / "verifier/evaluation/report.json"
                        if value.get("trial_path") and (trial / "verifier/evaluation/report.json").exists()
                        else recorded_path(value["evaluation_path"], jobs_dir.parent)
                        if value.get("evaluation_path")
                        else (
                            jobs_dir.parent
                            / "environments"
                            / trial.parent.name
                            / value["task_name"]
                            / "evaluation/report.json"
                        )
                    )
                    if source.exists() and json.loads(source.read_text()).get("schema") == HOSTED_SCHEMA:
                        found[trial] = source
            for item in value.values():
                visit(item)

    report = jobs_dir.parent / "report.json"
    if report.exists():
        visit(json.loads(report.read_text()))
    return sorted(found.items())


def render_hosted(evaluation: dict, source: Path, trial: Path) -> str:
    result = evaluation["result"]
    quality = result["quality"]
    lines = [
        GENERATED,
        "",
        "# Hosted evaluation",
        "",
        f"- **Reported execution:** {result['execution']}",
        f"- **Native execution:** {evaluation.get('native_execution')}",
        f"- **Terminal completion:** {evaluation.get('terminal_completion')}",
        f"- **Acceptance:** {result['acceptance']}",
        f"- **Quality:** {quality['status'] if quality else 'not provided'}",
    ]
    if quality:
        lines += [
            f"- **Score:** {quality.get('score_0_10')}",
            f"- **Normalized reward:** {quality.get('normalized_reward')}",
        ]
    lines += ["", f"[Authoritative report]({os.path.relpath(source, trial)})", f"SHA256: `{sha256(source)}`"]
    details = source.parent / "evaluation.json"
    if details.exists():
        lines += ["", f"[Evaluator details]({os.path.relpath(details, trial)})"]
    return "\n".join(lines) + "\n"


def table(rows: list[list[str]], headers: list[str]) -> str:
    cells = [headers, ["---"] * len(headers), *rows]
    return "\n".join("| " + " | ".join(row) + " |" for row in cells)


def escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def render(evaluation: dict, source: Path) -> str:
    score = evaluation.get("score_0_10")
    judge = evaluation.get("judge") or {}
    criteria = evaluation.get("criteria") or []
    acceptance = evaluation.get("project_acceptance") or {}

    deterministic = [c for c in criteria if c.get("evaluator") == "deterministic"]
    judged = [c for c in criteria if c.get("evaluator") != "deterministic"]
    earned = sum(float(c.get("points") or 0) for c in criteria)
    available = sum(float(c.get("weight") or 0) for c in criteria)

    lines = [
        GENERATED,
        "",
        f"# Business evaluation — {score}/10",
        "",
        f"- **Normalized reward:** {evaluation.get('normalized_reward')}",
        f"- **Status:** {evaluation.get('status')}",
        f"- **Evaluator execution gate:** {evaluation.get('execution_pass')}",
        f"- **Points:** {earned:g} of {available:g} ({len(deterministic)} deterministic, {len(judged)} judged)",
        f"- **Deterministic points:** {evaluation.get('deterministic_points')}",
        "",
        "Engine execution and acceptance are separate. A passing execution does not",
        "establish the score below, and the score does not claim the run was error-free.",
        "",
        "## Criteria",
        "",
        table(
            [
                [
                    escape(c.get("id")),
                    escape(c.get("question")),
                    escape(c.get("evaluator")),
                    escape(c.get("answer")),
                    f"{float(c.get('points') or 0):g} / {float(c.get('weight') or 0):g}",
                    escape(c.get("reason")),
                    escape(", ".join(c.get("evidence_refs") or [])) or "—",
                ]
                for c in criteria
            ],
            ["ID", "Question", "Evaluator", "Answer", "Points", "Reason", "Evidence"],
        ),
        "",
        f"Answer values: {json.dumps(evaluation.get('answer_values') or {})}",
        "",
    ]

    if acceptance:
        lines += [
            "## Project acceptance",
            "",
            f"- **Criterion:** {acceptance.get('criterion')}",
            f"- **Passed:** {acceptance.get('passed')}",
            f"- **Affects upstream score:** {acceptance.get('affects_upstream_score')}",
            f"- **Reason:** {acceptance.get('reason')}",
            "",
        ]

    if evaluation.get("judge_error"):
        lines += ["## Judge error", "", f"```\n{evaluation['judge_error']}\n```", ""]

    lines += [
        "## Provenance",
        "",
        f"- **Run:** `{evaluation.get('run_id')}`",
        f"- **Evaluation mode:** {evaluation.get('evaluation_mode')}",
        f"- **Judge:** {judge.get('mode')} / {judge.get('model')} / prompt {judge.get('prompt_version')}",
        f"- **Contract digest:** `{evaluation.get('contract_digest')}`",
        f"- **Run log digest:** `{evaluation.get('run_log_digest')}`",
        f"- **Source:** `{source.name}`, sha256 `{sha256(source)}`",
        "",
    ]
    return "\n".join(lines)


def reward_files(evaluation: dict) -> dict[str, dict]:
    """The viewer's documented reward files; its bundled frontend never reads them, so they are opt-in."""
    criteria = evaluation.get("criteria") or []
    return {
        "reward.json": {"reward": evaluation.get("normalized_reward")},
        "reward-details.json": {
            "reward": evaluation.get("normalized_reward"),
            "score_0_10": evaluation.get("score_0_10"),
            "components": [
                {
                    "name": c.get("id"),
                    "score": c.get("points"),
                    "max": c.get("weight"),
                    "answer": c.get("answer"),
                    "evaluator": c.get("evaluator"),
                    "rationale": c.get("reason"),
                }
                for c in criteria
            ],
        },
    }


def export_trial(
    evaluation_path: Path, *, force: bool, rewards: bool, dry_run: bool, trial: Path | None = None
) -> dict:
    trial = trial or evaluation_path.parents[2]
    evaluation = json.loads(evaluation_path.read_text())
    row: dict[str, Any] = {"trial": trial.name, "job": trial.parent.name, "written": [], "skipped": []}
    hosted = evaluation.get("schema") == HOSTED_SCHEMA
    if evaluation.get("schema") != SCHEMA and not hosted:
        row["skipped"].append({"path": "analysis.md", "reason": f"Unexpected schema {evaluation.get('schema')!r}"})
        return row

    content = render_hosted(evaluation, evaluation_path, trial) if hosted else render(evaluation, evaluation_path)
    targets: dict[Path, str] = {trial / "analysis.md": content}
    if rewards and hosted:
        row["skipped"].append({"path": "verifier/reward.json", "reason": "Hosted rewards remain recorded facts"})
    if rewards and not hosted:
        for name, value in reward_files(evaluation).items():
            targets[trial / "verifier" / name] = json_text(value)

    for path, content in targets.items():
        relative = str(path.relative_to(trial))
        if path.exists() and not force:
            row["skipped"].append({"path": relative, "reason": "Exists; use --force to replace"})
            continue
        if not dry_run:
            path.write_text(content)
        row["written"].append(relative)
    return row


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("jobs_dir", type=Path, help="A Harbor jobs directory, as passed to `harbor view`")
    parser.add_argument("--force", action="store_true", help="Replace a derived file this command wrote before")
    parser.add_argument("--rewards", action="store_true", help="Also write reward.json and reward-details.json")
    parser.add_argument("--dry-run", action="store_true", help="Report what would be written; change nothing")
    args = parser.parse_args()

    jobs_dir = args.jobs_dir.resolve()
    if not jobs_dir.is_dir():
        raise ValueError("Pass an existing Harbor jobs directory")
    evaluations = find_evaluations(jobs_dir)
    rows = [
        export_trial(path, trial=trial, force=args.force, rewards=args.rewards, dry_run=args.dry_run)
        for trial, path in evaluations
    ]
    print(
        json.dumps(
            {
                "jobs_dir": str(jobs_dir),
                "evaluations_found": len(evaluations),
                "dry_run": args.dry_run,
                "trials": rows,
            },
            indent=2,
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
