schema_version = "1.4"
artifacts = [
  {source="/logs/artifacts", destination="discarded-convention", exclude=["*"]},
  {source="/submission/config.yaml", destination="submission/config.yaml"}
]
[agent]
timeout_sec = 600
user = "1000"
[environment]
build_timeout_sec = 600
cpus = 1
memory_mb = 2048
[verifier]
timeout_sec = 1800
environment_mode = "separate"
[[verifier.collect]]
command = "python3 /opt/sapi-submission.py collect"
user = "root"
timeout_sec = 10
[verifier.environment]
cpus = 1
memory_mb = 2048

